# Generated by Django 5.2.3 on 2025-06-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='database_attendance',
        ),
    ]
