# Generated by Django 5.2.3 on 2025-06-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_attendance_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('for_teacher', models.BooleanField(default=False)),
            ],
        ),
    ]
