# Generated by Django 5.1.4 on 2025-07-12 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='detected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_detection_confidence',
            field=models.FloatField(default=0.0, help_text='Tỉ lệ phát hiện khuôn mặt (%)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='image_path',
            field=models.CharField(blank=True, help_text='Đường dẫn ảnh điểm danh', max_length=500),
        ),
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, help_text='Ghi chú'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder_path', models.CharField(help_text='Đường dẫn folder training', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='pending', max_length=20)),
                ('images_count', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.subject')),
            ],
            options={
                'db_table': 'database_training_session',
            },
        ),
    ]
