# Generated by Django 4.2.23 on 2025-07-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_teacher_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dayofbirth',
            field=models.CharField(blank=True, help_text='Format: dd/mm/yyyy', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dayofbirth',
            field=models.CharField(blank=True, help_text='Format: dd/mm/yyyy', max_length=10),
        ),
    ]
