# Generated by Django 5.2.3 on 2025-06-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
