# Generated by Django 4.2.23 on 2025-07-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_student_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_code',
            field=models.CharField(blank=True, help_text='12-digit teacher code', max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_code',
            field=models.CharField(blank=True, help_text='12-digit student code', max_length=12, null=True, unique=True),
        ),
    ]
